# Generated by Django 5.0.2 on 2024-03-19 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlistsDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playlist_video',
            unique_together={('playlist', 'video')},
        ),
        migrations.AlterField(
            model_name='playlist_video',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
